version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet

  reddit-summarizer:
    image: reddit-summarizer-flask
    env_file:
      - ./config/.reddit-ai-summarizer-backend.env
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - LOG_LEVEL=DEBUG
    networks:
      - webnet
networks:
  webnet:
    driver: overlay
